-- Booking/event numbering persistence.
-- Existing events receive a stable legacy number; newly created events use the
-- configured crm_numbering_sequences value generated by bookingRoutes.
ALTER TABLE events ADD COLUMN event_number TEXT;

UPDATE events
SET event_number = 'EV-LEGACY-' || printf('%04d', id)
WHERE event_number IS NULL;

CREATE UNIQUE INDEX IF NOT EXISTS idx_events_event_number
  ON events(event_number);